// Generated by https://quicktype.io

export interface CatEmpleadoResponse {
  data:          Empleado[];
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface Empleado {
  nunum_empleado_rr_hh:     number;
  nukidpersona:             number;
  nukidtipo_empleado:       number;
  nukidcategoria:           number;
  nukidtipo_contrato:       number;
  chcve_puesto:             number;
  nukidempresa:             number;
  nukidciudad:              number;
  nukidnivel_estudios:      number;
  nukidforma_pago:          number;
  nukidjornada:             number;
  nukiddepartamento:        number;
  nukidclasificacion:       number;
  nukidjefe_directo:        number;
  nukidunidad_negocio:      number;
  nukidtipo_contrato_sat:   number;
  nunum_empleado:           number;
  dtfecha_ingreso:          string;
  dtfecha_salida:           string;
  dtfecha_ultimo_reingreso: string;
  chnss:                    number;
  chemail_bovis:            string;
  chexperiencias:           null | string;
  chhabilidades:            null | string;
  churl_repositorio:        null | string;
  nusalario:                number;
  chprofesion:              string;
  nuantiguedad:             number;
  chturno:                  string;
  nuunidad_medica:          number;
  chregistro_patronal:      string;
  chcotizacion:             null | string;
  nuduracion:               number;
  boactivo:                 boolean;
  bodescuento_pension:      boolean;
  nuporcentaje_pension:     number;
  nufondo_fijo:             number;
  nucredito_infonavit:      number;
  chtipo_descuento:         null | string;
  nuvalor_descuento:        number;
  nuno_empleado_noi:        number;
  chrol:                    null;
}
