// Generated by https://quicktype.io

export interface CatEmpleadoResponse {
  data:          Empleado[];
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface Empleado {
  nunum_empleado_rr_hh:     number;
  nukidpersona:             number;
  nombre_persona:           string;
  nukidtipo_empleado:       number;
  nukidcategoria:           number;
  nukidtipo_contrato:       number;
  chcve_puesto:             number;
  nukidempresa:             number;
  nukidciudad:              number;
  nukidnivel_estudios:      number;
  nukidforma_pago:          number;
  nukidjornada:             number;
  nukiddepartamento:        number;
  nukidclasificacion:       number;
  nukidjefe_directo:        number;
  nukidunidad_negocio:      number;
  nukidtipo_contrato_sat:   number;
  nunum_empleado:           number;
  dtfecha_ingreso:          string;
  dtfecha_salida:           string;
  dtfecha_ultimo_reingreso: string;
  chnss:                    number;
  chemail_bovis:            string;
  chexperiencias:           null | string;
  chhabilidades:            null | string;
  churl_repositorio:        null | string;
  nusalario:                number;
  chprofesion:              string;
  nuantiguedad:             number;
  chturno:                  string;
  nuunidad_medica:          number;
  chregistro_patronal:      string;
  chcotizacion:             null | string;
  nuduracion:               number;
  boactivo:                 boolean;
  bodescuento_pension:      boolean;
  nuporcentaje_pension:     number;
  nufondo_fijo:             number;
  nucredito_infonavit:      number;
  chtipo_descuento:         null | string;
  nuvalor_descuento:        number;
  nuno_empleado_noi:        number;
  chrol:                    null;
}

export interface DiasHabilesResponse {
  data:          DiasHabiles;
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface DiasHabiles {
  id:           number;
  mes:          number;
  dias:         number;
  feriados:     number;
  sabados:      number;
  anio:         number;
  dias_habiles: number;
}

export interface EmpleadoProyectoResponse {
  data:          EmpleadoProyecto[];
  success:       boolean;
  message:       null;
  transactionId: null;
}

export interface EmpleadoProyecto {
  nunum_proyecto:                   number;
  chproyecto:                       string;
  chalcance:                        string;
  chcp:                             string;
  chciudad:                         string;
  nukidestatus:                     number;
  nukidsector:                      number;
  nukidtipo_proyecto:               number;
  nukidresponsable_preconstruccion: number;
  nukidresponsable_construiccion:   number;
  nukidresponsable_ehs:             number;
  nukidresponsable_supervisor:      number;
  nukidcliente:                     number;
  nukidempresa:                     number;
  nukidpais:                        number;
  nukiddirector_ejecutivo:          number;
  nucosto_promedio_m2:              number;
  dtfecha_ini:                      string;
  dtfecha_fin:                      string;
  nunum_empleado_rr_hh:             number;
  nuporcantaje_participacion:       number;
  chalias_puesto:                   string;
  chgrupo_proyecto:                 string;
}
